"use client";
// compoents
import Header from "@/components/header/Header";
import Complex from "@/components/Complex";
import ChooseUs from "@/components/ChooseUs";
import Catalog from "@/components/Catalog/Catalog";
import Brands from "@/components/Brands/Brands";
import News from "@/components/News/News";
import Map from "@/components/map/Map";
import Subscribe from "@/components/Subscribe";
import Footer from "@/components/Footer/Footer";
import Main from "@/components/CatalogPg/Main";
import AboutCompanyCtg from "@/components/CatalogPg/AboutCompanyCtg";
// title metadata
// import { Metadata } from "next";
import { catalogDataPg } from "@/data/CatalogPgData";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Каталог",
//   description: "Generated by create next app",
// };

const Home = () => {
  return (
    <>
      <div className="bg-[#F8F7F3FF]">
        {/* Header */}
        <header>
          {/* Components Header */}
          <Header />
        </header>
        {/* Main */}
        <main>
          {/* components banner */}

          {/* components Popular categories */}
          <Main />

          {/* Complex components */}
          <Complex />

          {/* Choose us compoents  */}
          <ChooseUs />

          {/* Catalog components */}
          <Catalog />

          {/* Brads components */}

          <Brands />

          {/* News components */}

          <News />

          {/* About company componets */}

          <AboutCompanyCtg />

          {/* Map and questions */}

          <Map />

          {/* SunScribe componets */}

          <Subscribe />
        </main>
        {/* Footer */}
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
};

export default Home;
